"""
Problem
A string is simply an ordered collection of symbols selected from some alphabet 
and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 
'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number 
of times that the symbols 'A', 'C', 'G', and 'T' occur in s
.

Sample Dataset
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

Sample Output
20 12 17 21
"""

DNA_string:str = 'AAGATACGGGTTGACATGTTACCATGCCGTCCATGAACGGTTGCATTACCGTCTCGACGTCGAGGTTTACAGCTAAATATTCCTGGAACCTCGTGTTGCCACGAGTATTTCAGCCTATACATAATGAACCCCTGTATTGACCCCTACTCCCAGGTTCGGTGGCTCAAAACTTAGCTACGACGTACCCCTGTACTCTGAGAGAAGTAACTTTCCTCTCGTCATTAAAAATCGCTGATGCAGTCATTCCAGACAGAATCCCACCGAGAAGCCACCTATTCTTTCTCGGCCTGCCGAGTGAGGAAAGCTTGTGTTCCAGCCATAGGCGTTGCCAAAGAATGCACTCTCTGTAGTGGAATCATTCTGTGACTCTGTTGTTCAAAAACAATATTTCAGCCCTTCGTCCGTCGGATGAATAGCAATGAATAGCTCTGCGCCCCTTGGAGCCTCCAAACCATGAAGTATGTACATGAAGAATCAGGAGCCTAGGAGGTCAGGGCGGTCCGTCGGCATACAAATCCCTTAGAGGAATTTCGGGAGAAAGGGCAGGCCATCTTTTGAATTGCCTTGCAAGGTTGCCCTAATGAACCGGCAGATAGAATTCGACTCTGGCTACCGACCGCCGAGCGAACGCGAGATGAAACAGAAAGTTTTTAGCAATATCTGATAGGCCTTTTCGCCCCGTGGTTATATAAAGGCTATGATTGTGATCTGGCAGCATCGTTGCTTCGACCAAATTCGTAGATGATTGTAGGAAGAGGGCTATTGGTATTCTGGGGCGAAGAGACCTCAATATGAAAGGTTAGACTCTCATTGTAGGATCTGCAATAGGCCGTCGCAGGGCAAATTGCATGATCTTGCCTTTCCTTTTTCCCAAGGTCCATCGCTGGGTTGTGCGGCCAGCGCCGGCGCGTGGTCTTAATAGCTAACGTCGATGAGCCCTTCCATACCCAGAGAAATTTCATCAGT'

if len(DNA_string)<=1000 and len(DNA_string)>=1:
    
    isDNA:bool = True
    
    A:int = 0
    C:int = 0
    G:int = 0
    T:int = 0
    
    for nucleotide in DNA_string:
        if nucleotide == 'A':
            A+=1
        elif nucleotide == 'C':
            C+=1
        elif nucleotide == 'G':
            G+=1
        elif nucleotide == 'T':
            T+=1
            
print(f'{A} {C} {G} {T}')

    

